all:
  children: 
    linux:
      hosts:
        glpi:
            ansible_host: '10.44.8.19'
            ansible_ssh_user: user1
            ansible_ssh_pass: $$password**
            #ansible_sudo_pass: $$password**
            ansible_ssh_timeout:  60
            become_user: root
            vars:
              ansible_python_interpreter: /usr/bin/python3

      children:
        sambaservers:
          hosts:
            kos-srv-kadyi:
              ansible_host: '10.44.86.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3

        
            kos-srv-makar:
              ansible_host: '10.44.82.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3
          
            kos-srv-mantur:
              ansible_host: '10.44.80.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3
            
            kos-srv-neya-netxms:
              ansible_host: '10.44.8.14'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3
          
            kos-srv-kologr:
              ansible_host: '10.44.88.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3
            
            kos-srv-antrop:
              ansible_host: '10.44.85.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python3

                      
            kos-srv-parfen:
              ansible_host: '10.44.83.5'
              ansible_ssh_user: user1
              ansible_ssh_pass: $$password**
              become_user: root
              vars:
                ansible_python_interpreter: /usr/bin/python2.7

                          

